---
- name: add repo
  command: yum-config-manager --add-repo=https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

- name: install consul
  yum:
    name: consul
    state: installed
  notify: restart consul
  
- name: add consul script
  template:
    src: consul.sh.j2
    dest: /etc/consul.d/consul.hcl
    owner: "root"
    group: "root"
    mode: u=rwx,g=r,o=r
  notify: restart consul  