---
- name: add repo
  command: yum-config-manager --add-repo=https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

- name: install consul
  yum:
    name: consul
    state: installed
  notify: restart consul