---
- name: add repo
  yum_repository:
    name: hashicorp repo
    baseurl: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

- name: install consul
  yum:
    name: consul
    state: installed
  notify: restart consul