# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vbguest.auto_update = false
  config.vm.box = "centos/7"

  config.vm.define "server" do |server|
    server.vm.hostname = "SERVER"
    server.vm.network "private_network", ip: "192.168.1.2"
	
	server.vm.provision "ansible" do |ansible|
      ansible.config_file = "ansible/ansible.cfg"
      ansible.playbook = "ansible/plays/server.yml"
      ansible.groups = {
        "servers" => ["server"],
#        "servers:vars" => {"crond__content" => "servers_value"}
      }
      ansible.host_vars = {
#        "server" => {"crond__content" => "server_value"}
      }
#      ansible.verbose = '-vvv'
    end
  end

  config.vm.define "agent1" do |agent1|
    agent1.vm.hostname = "AGENT1"
    agent1.vm.network "private_network", ip: "192.168.1.3"
	
	agent1.vm.provision "ansible" do |ansible|
      ansible.config_file = "ansible/ansible.cfg"
      ansible.playbook = "ansible/plays/agent1.yml"
      ansible.groups = {
        "agent1" => ["agent1"],
#        "agent1:vars" => {"crond__content" => "agent1_value"}
      }
      ansible.host_vars = {
#        "agent1" => {"crond__content" => "agent1_value"}
      }
#      ansible.verbose = '-vvv'
    end
  end

  config.vm.define "agent2" do |agent2|
    agent2.vm.hostname = "AGENT2"
    agent2.vm.network "private_network", ip: "192.168.1.4"
	
	agent2.vm.provision "ansible" do |ansible|
      ansible.config_file = "ansible/ansible.cfg"
      ansible.playbook = "ansible/plays/agent2.yml"
      ansible.groups = {
        "agent2" => ["agent2"],
#        "agent2:vars" => {"crond__content" => "agent2_value"}
      }
      ansible.host_vars = {
#        "agent2" => {"crond__content" => "agent2_value"}
      }
#      ansible.verbose = '-vvv'
    end
  end
  
  config.vm.provider :virtualbox do |virtualbox, override|
    virtualbox.customize ["modifyvm", :id, "--memory", 2048]
  end
  
  config.vm.provider :lxc do |lxc, override|
    override.vm.box = "visibilityspots/centos-7.x-minimal"
  end

end